### ISSUE TITLE
Pester module cannot be retrieved

### ISSUE THREAD

**Issue by kjanos0502** [pester/AzureDevOpsExtension#23]
### Where are you running it?
- Azure DevOps Service (VSTS)

### Version of Extension/Task
10.0.3

### Expected behaviour and actual behaviour
Pester Test Runner should not throw errors when using the new version

![image](https://user-images.githubusercontent.com/26416927/82917383-a6665080-9f73-11ea-8793-dbada6f0f1f3.png)

### Steps to reproduce the problem
All I did was switching the task from v9 to v10 in a working build pipeline.
The issue is happening on Azure Pipelines agents and self-hosted agents as well.

Is it something on our end?

**Comment by ChrisLGardner** [comment]
The issue you're seeing is that Pester 5 hasn't been published yet so the v10 of the task won't currently work. I published it because it was part of the work to lock down v9 of the extension to pester 4.

If you haven't migrated your tests to Pester 5 yet then I wouldn't upgrade the version of the extension just yet.

**Comment by kjanos0502** [comment]
Awesome, thanks for the quick reply!
